CREATE TABLE orders
(
    id      BIGINT AUTO_INCREMENT PRIMARY KEY,
    moment  TIMESTAMP    NOT NULL,
    status  ENUM('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELED') NOT NULL,
    user_id BIGINT,
    FOREIGN KEY (user_id) REFERENCES users (id)
);